/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxi.simulator.pkg2;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static taxi.simulator.pkg2.AnimationTest.rn;
import static taxi.simulator.pkg2.AnimationTest.size;
import java.util.*;

/**
 *
 * @author Asus
 */
public class PassengerNum extends javax.swing.JFrame {

    Scanner sc = new Scanner(System.in);
    int CustNumber;

    /**
     * Creates new form PassengerNum
     */
    
    public PassengerNum() {
        initComponents();
    }
    
    public int getCustNumber() {
        return this.CustNumber;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CustNum = new javax.swing.JTextField();
        SaveCustNum = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Number of Passenger:");

        SaveCustNum.setText("OK");
        SaveCustNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveCustNumActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel2.setText("(Maximum 4 passengers)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(SaveCustNum))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CustNum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SaveCustNum)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveCustNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveCustNumActionPerformed
        int size = 5;
        String[][] mapArr = new String[size][size];
        Taxi taxi = new Taxi(mapArr);

        this.CustNumber = Integer.parseInt(this.CustNum.getText());
        System.out.println(this.CustNumber);
        this.setVisible(false);
        if(this.CustNumber > 4){
            JOptionPane.showMessageDialog(this, "Over the passenger limit.", "Error", JOptionPane.ERROR_MESSAGE);
            PassengerNum passNum=new PassengerNum();
            passNum.setVisible(true);
        }
        else{

        Source UI = new Source(0, CustNumber);
        UI.setVisible(true);
        }
       
        
        
//        Passenger P = new Passenger();
//        
//        for (int i = 0; i < this.CustNumber; i++) {
//            System.out.print("\nEnter name: ");
//            name = sc.next();
//            System.out.print("Enter " + name + "'s x-coordinate source: ");
//            XSource = sc.nextInt();
////            XSource = rn(size);
//            System.out.print("Enter " + name + "'s y-coordinate source: ");
//            YSource = sc.nextInt();
////            YSource = rn(size);
//            System.out.print("Enter " + name + "'s x-coordinate destination: ");
//            XDest = sc.nextInt();
////            XDest = rn(size);
//            System.out.print("Enter " + name + "'s y-coordinate destination: ");
//            YDest = sc.nextInt();
//            P.addPassenger(name, XSource, YSource, XDest, YDest, mapArr, taxi);
//        }
//        taxi.printMap(mapArr);
//        taxi.sendPassengers();
        

         //animationPart
//        AnimationTest test = new AnimationTest(taxi.taxiMovement);
//        JFrame jf = new JFrame();
//        jf.setTitle("Test");
//        jf.setSize(size * 100, 20 + size * 100);
//        jf.setVisible(true);
//        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        jf.add(test);
        
    }//GEN-LAST:event_SaveCustNumActionPerformed
        public void add(String name,int srcX, int srcY, int destX, int destY, String[][] mapArr, Taxi taxi){
            int size=5;
            Passenger a=new Passenger(name, srcX, srcY, destX, destY, mapArr, taxi);
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerNum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerNum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustNum;
    private javax.swing.JButton SaveCustNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
