/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxi.simulator.pkg2;

import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class UserInformation extends javax.swing.JFrame {
    int CustNum;
    int count=0;
        String[] name=new String[4];
        int[] XSource=new int[4];
        int[] YSource=new int[4];
        int[] XDest=new int[4];
        int[] YDest=new int[4];
    Scanner sc = new Scanner(System.in);
    final Passenger P = new Passenger();
    PassengerNum a=new PassengerNum();

    /**
     * Creates new form UserInformation
     * @param count
     * @param CustNum
     */
    public UserInformation(int count, int CustNum) {
        this.count=count;
        this.CustNum=CustNum;
        initComponents();
    }

    public UserInformation(int count,int CustNum ,String[] name,int[] srcX, int[] srcY, int[] destX, int[] destY, String[][] mapArr, Taxi taxi) {
         this.count=count;
        this.CustNum=CustNum;
        this.name=name;
        this.XSource=srcX;
        this.XSource=srcY;
        this.XDest=destX;
        this.YDest=destY;
        initComponents();
    }
    
    

    public int coordinate(String e) {
        int coor;
        if (e.equals("KTM Sultan Ismail")) {
            coor = 0;
            return coor;
        }
        if (e.equals("1")) {
            coor = 1;
            return coor;
        }
        if (e.equals("Kg. Padang Merbok")) {
            coor = 2;
            return coor;
        }
        if (e.equals("Dataran Merdeka")) {
            coor = 3;
            return coor;
        }
        if (e.equals("Central Market")) {
            coor = 4;
            return coor;
        }
        if (e.equals("Quill City Mall")) {
            coor = 10;
            return coor;
        }
        if (e.equals("KTM Dang Wangi")) {
            coor = 11;
            return coor;
        }
        if (e.equals("Masjid India")) {
            coor = 12;
            return coor;
        }
        if (e.equals("Masjid Jamek")) {
            coor = 13;
            return coor;
        }
        if (e.equals("KTM Plaza Rakyat")) {
            coor = 14;
            return coor;
        }
        if (e.equals("Kg. Baru")) {
            coor = 20;
            return coor;
        }
        if (e.equals("Concorde Hotel")) {
            coor = 31;
            return coor;
        }
        if (e.equals("Menara KL")) {
            coor = 32;
            return coor;
        }
        if (e.equals("Invito Hotel")) {
            coor = 23;
            return coor;
        }
        if (e.equals("Low Yat")) {
            coor = 24;
            return coor;
        }
        if (e.equals("2")) {
            coor = 30;
            return coor;
        }
        if (e.equals("Aquaria KLCC")) {
            coor = 31;
            return coor;
        }
        if (e.equals("LRT Raja Chulan")) {
            coor = 32;
            return coor;
        }
        if (e.equals("Pavillion")) {
            coor = 33;
            return coor;
        }
        if (e.equals("3")) {
            coor = 34;
            return coor;
        }
        if (e.equals("4")) {
            coor = 40;
            return coor;
        }
        if (e.equals("Masjid As-Syakirin")) {
            coor = 41;
            return coor;
        }
        if (e.equals("Royal Chulan Kuala Lumpur")) {
            coor = 42;
            return coor;
        }
        if (e.equals("Prince Court Medical Centre")) {
            coor = 43;
            return coor;
        }
        if (e.equals("RHB Kuala Lumpur")) {
            coor = 44;
            return coor;
        }
        return 99;
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        destination = new javax.swing.JTextField();
        pickup = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nameS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        jLabel2.setText("Pickup Location:");

        jLabel3.setText("Destination Location: ");

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel4.setText("Passenger ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(save)
                    .addComponent(destination)
                    .addComponent(pickup)
                    .addComponent(nameS, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pickup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(save)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        
        String location;
        int coordin;
        boolean status=false;
        String[][] mapArr = new String[5][5];
        Taxi taxi = new Taxi(mapArr);
        PassengerNum pn = new PassengerNum();
            this.jLabel4.setText("Passenger " + (count + 1));
            name[count] = this.nameS.getText();
            location = this.pickup.getText();
            coordin = coordinate(location);
            XSource [count]= coordin / 10;
            YSource[count] = coordin % 10;
            location = this.destination.getText();
            coordin = coordinate(location);
            XDest[count] = coordin / 10;
            YDest[count] = coordin % 10;
            this.setVisible(false);
            
        if(count>=CustNum-1){
            status=true;
            
        }
        
            
            if(!status){
                try{
                    UserInformation UI=new UserInformation(count+1,CustNum,name, XSource, YSource, XDest, YDest, mapArr, taxi);
                    UI.setVisible(true);
                }
                catch(Exception e){
                    System.out.println("Error");
                }
            }
        
        if(status){
            for (int i = 0; i < CustNum; i++) {
                P.addPassenger(name[i], XSource[i], YSource[i], XDest[i], YDest[i], mapArr, taxi);
                
            }
            taxi.printMap(mapArr);
            taxi.sendPassengers();
            int size=5;

            AnimationTest test = new AnimationTest(taxi.taxiMovement);
                    JFrame jf = new JFrame();
                    jf.setTitle("Test");
                    jf.setSize(size*100,20+size*100);
                    jf.setVisible(true);
                    jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    jf.add(test);
        }
    }//GEN-LAST:event_saveActionPerformed

              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new UserInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField destination;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameS;
    private javax.swing.JTextField pickup;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables

}
